@echo off
REM Start the app in DEV DEMO mode (Mocks ON)
set USE_MOCKS=true
set FLASK_DEBUG=1
REM Optional: leave upstreams empty so all endpoints use mocks
REM set CONTEXT_STATE_UPSTREAM=
REM set CONTEXT_SYSTEM_UPSTREAM=
REM set CONTEXT_METRICS_SELECT_UPSTREAM=
REM set CONTEXT_FRAMEWORK_COMPETENCIES_UPSTREAM=
REM set FRAMEWORKS_TREE_UPSTREAM=
REM set SMART_RECS_GENERATE_UPSTREAM=
REM set SMART_RECS_INTERACT_UPSTREAM=
REM set DYNAMIC_REPORTS_START_UPSTREAM=
REM set DYNAMIC_REPORTS_STATUS_UPSTREAM=

python app.py
