"""Add api_key to admin_users

Revision ID: 92e8a3144dc5
Revises: b00debb5bc67
Create Date: 2025-09-01 10:46:55.312696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e8a3144dc5'
down_revision = 'b00debb5bc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_admin_users_api_key', ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admin_users_api_key', type_='unique')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
