"""Add frameworks, competencies, and competency_metrics

Revision ID: b00debb5bc67
Revises: a2c9f1e3b7a1
Create Date: 2025-08-29 17:48:53.321835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00debb5bc67'
down_revision = 'a2c9f1e3b7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competencies_framework_id'))
        batch_op.drop_index(batch_op.f('ix_competencies_slug'))

    op.drop_table('competencies')
    with op.batch_alter_table('report_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_analytics_report_id'))

    op.drop_table('report_analytics')
    op.drop_table('metrics')
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frameworks_slug'))

    op.drop_table('frameworks')
    op.drop_table('metric_types')
    op.drop_table('ld_outcomes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_user_id'))

    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    op.drop_table('user_contexts')
    op.drop_table('users')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_id'))

    op.drop_table('user_sessions')
    op.drop_table('event_analyses')
    op.drop_table('competency_metrics')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_template_type'))

    op.drop_table('report_templates')
    op.drop_table('metric_selections')
    with op.batch_alter_table('dynamic_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_reports_session_id'))

    op.drop_table('dynamic_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('selected_outcomes', sa.TEXT(), nullable=True),
    sa.Column('selected_metrics', sa.TEXT(), nullable=True),
    sa.Column('ai_recommendations', sa.TEXT(), nullable=True),
    sa.Column('generation_context', sa.TEXT(), nullable=True),
    sa.Column('executive_summary', sa.TEXT(), nullable=True),
    sa.Column('strategy_context', sa.TEXT(), nullable=True),
    sa.Column('metric_analysis', sa.TEXT(), nullable=True),
    sa.Column('ai_insights', sa.TEXT(), nullable=True),
    sa.Column('implementation_roadmap', sa.TEXT(), nullable=True),
    sa.Column('success_metrics', sa.TEXT(), nullable=True),
    sa.Column('appendices', sa.TEXT(), nullable=True),
    sa.Column('generation_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('generation_progress', sa.INTEGER(), nullable=False),
    sa.Column('estimated_pages', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('pdf_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('download_count', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('generated_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamic_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_reports_session_id'), ['session_id'], unique=False)

    op.create_table('metric_selections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('metric_id', sa.INTEGER(), nullable=False),
    sa.Column('selection_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('selected_at', sa.DATETIME(), nullable=False),
    sa.Column('deselected_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('context_tags', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('template_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sections', sa.TEXT(), nullable=True),
    sa.Column('styling', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_template_type'), ['template_type'], unique=False)

    op.create_table('competency_metrics',
    sa.Column('competency_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('competency_id', 'metric_id')
    )
    op.create_table('event_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_description', sa.TEXT(), nullable=False),
    sa.Column('analysis_result', sa.TEXT(), nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_identifier', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('last_activity', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_session_id'), ['session_id'], unique=1)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_contexts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('context_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('context_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('context_data', sa.TEXT(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'context_type', 'context_key')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)

    op.create_table('ld_outcomes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('level', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metric_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('frameworks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_builtin', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frameworks_slug'), ['slug'], unique=1)

    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('outcome_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_type_id', sa.INTEGER(), nullable=False),
    sa.Column('measurement_method', sa.TEXT(), nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=200), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(length=50), nullable=True),
    sa.Column('example', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('data_collection', sa.VARCHAR(length=100), nullable=True),
    sa.Column('success_criteria', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['ld_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('outcome_distribution', sa.TEXT(), nullable=True),
    sa.Column('metric_type_distribution', sa.TEXT(), nullable=True),
    sa.Column('ai_recommendation_count', sa.INTEGER(), nullable=False),
    sa.Column('complexity_score', sa.FLOAT(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['dynamic_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_analytics_report_id'), ['report_id'], unique=False)

    op.create_table('competencies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('framework_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competencies_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_competencies_framework_id'), ['framework_id'], unique=False)

    # ### end Alembic commands ###
