"""Initial schema sync (add metrics.data_collection, etc.)

Revision ID: f541db0413b2
Revises: 
Create Date: 2025-08-26 04:10:44.684472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f541db0413b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        # SQLite requires a server_default when adding a NOT NULL column.
        # Use 1 (true) to match the model's default, then drop the default below.
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    with op.batch_alter_table('ld_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=100), nullable=True))

    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_collection', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('success_criteria', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###
    # Remove the temporary default now that existing rows have been backfilled
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_column('success_criteria')
        batch_op.drop_column('data_collection')

    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('ld_outcomes', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('category')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
