"""add role profiling (KSAO) tables

Revision ID: rp_20250915
Revises: mrg_20250911
Create Date: 2025-09-15 14:25:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
down_revision = 'mrg_20250911'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        'role_profiles',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=200), nullable=False, unique=True),
        sa.Column('description', sa.Text()),
        sa.Column('department', sa.String(length=200)),
{{ ... }}
    op.create_index('ix_role_assignments_role_profile_id', 'role_assignments', ['role_profile_id'])
    op.create_index('ix_role_assignments_person_identifier', 'role_assignments', ['person_identifier'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_assignments_person_identifier', table_name='role_assignments')
    op.drop_index('ix_role_assignments_role_profile_id', table_name='role_assignments')
    op.drop_table('role_assignments')

    op.drop_index('ix_role_competency_targets_competency_id', table_name='role_competency_targets')
{{ ... }}
    op.drop_table('role_competency_targets')

    op.drop_index('ix_role_other_requirements_role_profile_id', table_name='role_other_requirements')
    op.drop_table('role_other_requirements')

    op.drop_index('ix_role_abilities_role_profile_id', table_name='role_abilities')
    op.drop_table('role_abilities')

    op.drop_index('ix_role_skills_role_profile_id', table_name='role_skills')
    op.drop_table('role_skills')

    op.drop_index('ix_role_knowledge_role_profile_id', table_name='role_knowledge')
    op.drop_table('role_knowledge')

    op.drop_table('role_profiles')
