"""
Map existing Metric rows to seeded Competencies using simple name-based heuristics.
Run: PYTHONPATH="<project>/ld-metrics-translator" python scripts/map_competency_metrics.py
"""
from typing import Dict, List
from sqlalchemy import or_

from app import create_app, db
from app.models import Framework, Competency, Metric


def find_metric_by_keywords(keywords: List[str]) -> Metric | None:
    query = Metric.query
    filters = []
    for kw in keywords:
        like = f"%{kw}%"
        filters.append(Metric.name.ilike(like))
        filters.append(Metric.description.ilike(like))
    return query.filter(or_(*filters)).first()


def attach_metric(comp: Competency, metric: Metric) -> bool:
    if not metric:
        return False
    if metric in comp.metrics:
        return False
    comp.metrics.append(metric)
    db.session.add(comp)
    return True


def map_for_framework(slug: str, mapping: Dict[str, List[List[str]]]):
    fw = Framework.query.filter_by(slug=slug).first()
    if not fw:
        print(f"Framework not found: {slug}")
        return
    by_slug = {c.slug: c for c in fw.competencies}
    total_added = 0
    for comp_slug, keyword_groups in mapping.items():
        comp = by_slug.get(comp_slug)
        if not comp:
            print(f" Competency not found: {comp_slug}")
            continue
        added_here = 0
        for keywords in keyword_groups:
            m = find_metric_by_keywords(keywords)
            if m and attach_metric(comp, m):
                added_here += 1
        if added_here:
            print(f" {comp.slug}: linked {added_here} metrics (now {len(comp.metrics)} total)")
        total_added += added_here
    if total_added:
        db.session.commit()
    print(f"Framework '{slug}': added {total_added} metric links")


def main():
    app = create_app()
    with app.app_context():
        # Heuristic mappings (keywords OR across list entries)
        goleman_map = {
            # slugs generated by seed script from names
            "self-awareness": [
                ["360", "feedback"],
                ["self", "assessment"],
                ["pulse", "survey"],
            ],
            "self-management": [
                ["goal", "completion"],
                ["on-time", "delivery"],
                ["absenteeism"],
            ],
            "social-awareness": [
                ["employee", "engagement"],
                ["eNPS"],
                ["peer", "feedback"],
            ],
            "relationship-management": [
                ["manager", "feedback"],
                ["collaboration"],
                ["cross", "functional"],
            ],
        }
        map_for_framework("goleman-emotional-intelligence", goleman_map)

        situational_map = {
            "directing": [
                ["time", "to", "productivity"],
                ["error", "rate"],
            ],
            "coaching": [
                ["coaching"],
                ["learning", "retention"],
            ],
            "supporting": [
                ["team", "satisfaction"],
                ["collaboration"],
            ],
            "delegating": [
                ["delegation"],
                ["cycle", "time"],
            ],
        }
        map_for_framework("situational-leadership", situational_map)


if __name__ == "__main__":
    main()
